/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export interface SingleProcess {
  pid: number
  name: string
}
export function getAll(): Array<SingleProcess>
export function getParent(pid: number): SingleProcess | null
export function getAllInPidList(pid: number): Array<SingleProcess>
export interface TreeProcess {
  pid: number
  name: string
  parentPid: number
  children: Array<TreeProcess>
}
